/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Student } from "../types";

export const DEFAULT_STUDENTS: Student[] = [
  {
    id: "stud_01",
    studentCode: "037206123456",
    fullName: "Nguyễn Minh Anh",
    dob: "2011-05-15",
    gender: "Nam",
    school: "Trường PTDTBT Tiểu Học và THCS Suối Lư",
    className: "9A1",
    gradeLevel: "9",
    academicYear: "2025-2026",
    academicGrade: "Tốt",
    behaviorGrade: "Tốt",
    behaviorGradeSummer: "Không",
    daysAbsent: 1,
    daysAbsentUnexcused: 0,
    distinction: "Học sinh Xuất sắc",
    notes: "Học sinh tích cực tham gia các phong trào trường lớp, đạt giải Nhì kì thi HSG Toán cấp Quận.",
    verificationToken: "VERIFY-HS202601-CHUVANAN-9A1-2526",
    subjects: [
      { subjectId: "toan", subjectName: "Toán học", isEvaluatedByScore: true, mid1: 9.5, end1: 10, semester1: 9.8, mid2: 10, end2: 9.5, semester2: 9.7, yearAvg: 9.8 },
      { subjectId: "ly_dia", subjectName: "Lịch sử và Địa lí", isEvaluatedByScore: true, mid1: 9.0, end1: 9.5, semester1: 9.3, mid2: 9.5, end2: 9.0, semester2: 9.2, yearAvg: 9.3 },
      { subjectId: "khtn", subjectName: "Khoa học tự nhiên", isEvaluatedByScore: true, mid1: 9.2, end1: 9.6, semester1: 9.4, mid2: 9.5, end2: 9.8, semester2: 9.7, yearAvg: 9.6 },
      { subjectId: "tin", subjectName: "Tin học", isEvaluatedByScore: true, mid1: 10, end1: 10, semester1: 10, mid2: 9.5, end2: 10, semester2: 9.8, yearAvg: 9.9 },
      { subjectId: "van", subjectName: "Ngữ văn", isEvaluatedByScore: true, mid1: 8.5, end1: 9.0, semester1: 8.7, mid2: 8.5, end2: 9.2, semester2: 8.9, yearAvg: 8.8 },
      { subjectId: "anh", subjectName: "Ngoại ngữ", isEvaluatedByScore: true, mid1: 9.5, end1: 9.8, semester1: 9.7, mid2: 9.5, end2: 10, semester2: 9.8, yearAvg: 9.8 },
      { subjectId: "gdcd", subjectName: "GDCD", isEvaluatedByScore: true, mid1: 9.0, end1: 9.5, semester1: 9.3, mid2: 9.5, end2: 9.5, semester2: 9.5, yearAvg: 9.4 },
      { subjectId: "cong_nghe", subjectName: "Công nghệ", isEvaluatedByScore: true, mid1: 9.0, end1: 9.0, semester1: 9.0, mid2: 9.0, end2: 9.5, semester2: 9.3, yearAvg: 9.2 },
      { subjectId: "the_duc", subjectName: "Giáo dục thể chất", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
      { subjectId: "nghe_thuat", subjectName: "Nghệ thuật", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
      { subjectId: "gd_dia_phuong", subjectName: "Nội dung giáo dục của địa phương", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
      { subjectId: "trai_nghiem", subjectName: "Hoạt động trải nghiệm, hướng nghiệp", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
    ]
  },
  {
    id: "stud_02",
    studentCode: "037206123457",
    fullName: "Trần Thị Mai Phương",
    dob: "2011-10-22",
    gender: "Nữ",
    school: "Trường PTDTBT Tiểu Học và THCS Suối Lư",
    className: "9A1",
    gradeLevel: "9",
    academicYear: "2025-2026",
    academicGrade: "Khá",
    behaviorGrade: "Tốt",
    behaviorGradeSummer: "Không",
    daysAbsent: 2,
    daysAbsentUnexcused: 0,
    distinction: "Học sinh Giỏi",
    notes: "Ngoan ngoãn, có tinh thần tương thân tương ái, có tiến bộ vượt bậc ở môn học Ngữ Văn.",
    verificationToken: "VERIFY-HS202602-CHUVANAN-9A1-2526",
    subjects: [
      { subjectId: "toan", subjectName: "Toán học", isEvaluatedByScore: true, mid1: 7.5, end1: 8.0, semester1: 7.8, mid2: 8.0, end2: 8.5, semester2: 8.3, yearAvg: 8.1 },
      { subjectId: "ly_dia", subjectName: "Lịch sử và Địa lí", isEvaluatedByScore: true, mid1: 8.0, end1: 7.5, semester1: 7.7, mid2: 8.0, end2: 8.0, semester2: 8.0, yearAvg: 7.9 },
      { subjectId: "khtn", subjectName: "Khoa học tự nhiên", isEvaluatedByScore: true, mid1: 7.8, end1: 8.2, semester1: 8.0, mid2: 8.0, end2: 8.2, semester2: 8.1, yearAvg: 8.1 },
      { subjectId: "tin", subjectName: "Tin học", isEvaluatedByScore: true, mid1: 8.0, end1: 8.5, semester1: 8.3, mid2: 9.0, end2: 9.0, semester2: 9.0, yearAvg: 8.7 },
      { subjectId: "van", subjectName: "Ngữ văn", isEvaluatedByScore: true, mid1: 8.0, end1: 8.5, semester1: 8.3, mid2: 8.5, end2: 8.5, semester2: 8.5, yearAvg: 8.4 },
      { subjectId: "anh", subjectName: "Ngoại ngữ", isEvaluatedByScore: true, mid1: 8.5, end1: 8.0, semester1: 8.2, mid2: 8.5, end2: 9.0, semester2: 8.8, yearAvg: 8.5 },
      { subjectId: "gdcd", subjectName: "GDCD", isEvaluatedByScore: true, mid1: 8.5, end1: 9.0, semester1: 8.8, mid2: 9.0, end2: 9.0, semester2: 9.0, yearAvg: 8.9 },
      { subjectId: "cong_nghe", subjectName: "Công nghệ", isEvaluatedByScore: true, mid1: 8.0, end1: 8.0, semester1: 8.0, mid2: 8.5, end2: 8.0, semester2: 8.2, yearAvg: 8.1 },
      { subjectId: "the_duc", subjectName: "Giáo dục thể chất", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
      { subjectId: "nghe_thuat", subjectName: "Nghệ thuật", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
      { subjectId: "gd_dia_phuong", subjectName: "Nội dung giáo dục của địa phương", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
      { subjectId: "trai_nghiem", subjectName: "Hoạt động trải nghiệm, hướng nghiệp", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
    ]
  },
  {
    id: "stud_03",
    studentCode: "037206123458",
    fullName: "Phạm Quốc Bảo",
    dob: "2012-02-03",
    gender: "Nam",
    school: "Trường PTDTBT Tiểu Học và THCS Suối Lư",
    className: "8B2",
    gradeLevel: "8",
    academicYear: "2025-2026",
    academicGrade: "Đạt",
    behaviorGrade: "Khá",
    behaviorGradeSummer: "Không",
    daysAbsent: 4,
    daysAbsentUnexcused: 1,
    distinction: "Không",
    notes: "Cần chú ý tập trung nghe giảng hơn. Có năng khiếu thể thao, xung kích trong phong trào thể dục thể thao của trường.",
    verificationToken: "VERIFY-HS202603-CHUVANAN-8B2-2526",
    subjects: [
      { subjectId: "toan", subjectName: "Toán học", isEvaluatedByScore: true, mid1: 5.0, end1: 5.5, semester1: 5.3, mid2: 6.0, end2: 5.8, semester2: 5.9, yearAvg: 5.6 },
      { subjectId: "ly_dia", subjectName: "Lịch sử và Địa lí", isEvaluatedByScore: true, mid1: 6.0, end1: 6.5, semester1: 6.3, mid2: 6.0, end2: 6.5, semester2: 6.3, yearAvg: 6.3 },
      { subjectId: "khtn", subjectName: "Khoa học tự nhiên", isEvaluatedByScore: true, mid1: 5.8, end1: 6.0, semester1: 5.9, mid2: 6.2, end2: 6.0, semester2: 6.1, yearAvg: 6.0 },
      { subjectId: "tin", subjectName: "Tin học", isEvaluatedByScore: true, mid1: 6.5, end1: 7.0, semester1: 6.8, mid2: 7.0, end2: 6.5, semester2: 6.7, yearAvg: 6.7 },
      { subjectId: "van", subjectName: "Ngữ văn", isEvaluatedByScore: true, mid1: 6.0, end1: 5.5, semester1: 5.7, mid2: 5.5, end2: 6.2, semester2: 5.9, yearAvg: 5.8 },
      { subjectId: "anh", subjectName: "Ngoại ngữ", isEvaluatedByScore: true, mid1: 5.5, end1: 5.0, semester1: 5.2, mid2: 5.5, end2: 6.0, semester2: 5.8, yearAvg: 5.5 },
      { subjectId: "gdcd", subjectName: "GDCD", isEvaluatedByScore: true, mid1: 7.0, end1: 6.5, semester1: 6.7, mid2: 7.0, end2: 7.5, semester2: 7.3, yearAvg: 7.0 },
      { subjectId: "cong_nghe", subjectName: "Công nghệ", isEvaluatedByScore: true, mid1: 6.0, end1: 6.0, semester1: 6.0, mid2: 6.5, end2: 6.0, semester2: 6.2, yearAvg: 6.1 },
      { subjectId: "the_duc", subjectName: "Giáo dục thể chất", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
      { subjectId: "nghe_thuat", subjectName: "Nghệ thuật", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
      { subjectId: "gd_dia_phuong", subjectName: "Nội dung giáo dục của địa phương", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
      { subjectId: "trai_nghiem", subjectName: "Hoạt động trải nghiệm, hướng nghiệp", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
    ]
  },
  {
    id: "stud_04",
    studentCode: "037206123459",
    fullName: "Lê Hoàng Long",
    dob: "24-09-12", // simplified/flexible search format
    gender: "Nam",
    school: "Trường PTDTBT Tiểu Học và THCS Suối Lư",
    className: "7C3",
    gradeLevel: "7",
    academicYear: "2025-2026",
    academicGrade: "Tốt",
    behaviorGrade: "Tốt",
    behaviorGradeSummer: "Không",
    daysAbsent: 0,
    daysAbsentUnexcused: 0,
    distinction: "Học sinh Xuất sắc",
    notes: "Khả năng phân tích logic xuất sắc, đạt giải Ba học sinh giỏi môn Khoa học tự nhiên của thành phố.",
    verificationToken: "VERIFY-HS202604-CHUVANAN-7C3-2526",
    subjects: [
      { subjectId: "toan", subjectName: "Toán học", isEvaluatedByScore: true, mid1: 9.5, end1: 9.5, semester1: 9.5, mid2: 10, end2: 10, semester2: 10, yearAvg: 9.8 },
      { subjectId: "ly_dia", subjectName: "Lịch sử và Địa lí", isEvaluatedByScore: true, mid1: 9.0, end1: 9.0, semester1: 9.0, mid2: 9.5, end2: 9.0, semester2: 9.2, yearAvg: 9.1 },
      { subjectId: "khtn", subjectName: "Khoa học tự nhiên", isEvaluatedByScore: true, mid1: 9.8, end1: 10, semester1: 9.9, mid2: 10, end2: 9.8, semester2: 9.9, yearAvg: 9.9 },
      { subjectId: "tin", subjectName: "Tin học", isEvaluatedByScore: true, mid1: 9.5, end1: 10, semester1: 9.8, mid2: 9.5, end2: 10, semester2: 9.8, yearAvg: 9.8 },
      { subjectId: "van", subjectName: "Ngữ văn", isEvaluatedByScore: true, mid1: 8.5, end1: 8.5, semester1: 8.5, mid2: 8.5, end2: 9.0, semester2: 8.8, yearAvg: 8.7 },
      { subjectId: "anh", subjectName: "Ngoại ngữ", isEvaluatedByScore: true, mid1: 9.0, end1: 9.5, semester1: 9.3, mid2: 9.5, end2: 9.5, semester2: 9.5, yearAvg: 9.4 },
      { subjectId: "gdcd", subjectName: "GDCD", isEvaluatedByScore: true, mid1: 9.0, end1: 9.5, semester1: 9.3, mid2: 9.0, end2: 9.5, semester2: 9.3, yearAvg: 9.3 },
      { subjectId: "cong_nghe", subjectName: "Công nghệ", isEvaluatedByScore: true, mid1: 9.0, end1: 9.0, semester1: 9.0, mid2: 9.0, end2: 9.5, semester2: 9.3, yearAvg: 9.2 },
      { subjectId: "the_duc", subjectName: "Giáo dục thể chất", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
      { subjectId: "nghe_thuat", subjectName: "Nghệ thuật", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
      { subjectId: "gd_dia_phuong", subjectName: "Nội dung giáo dục của địa phương", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
      { subjectId: "trai_nghiem", subjectName: "Hoạt động trải nghiệm, hướng nghiệp", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
    ]
  },
  {
    id: "stud_05",
    studentCode: "037206123460",
    fullName: "Vũ Ngân Chi",
    dob: "2014-04-04",
    gender: "Nữ",
    school: "Trường PTDTBT Tiểu Học và THCS Suối Lư",
    className: "6A5",
    gradeLevel: "6",
    academicYear: "2025-2026",
    academicGrade: "Chưa đạt",
    behaviorGrade: "Đạt",
    behaviorGradeSummer: "Chưa đạt",
    daysAbsent: 12,
    daysAbsentUnexcused: 5,
    distinction: "Không",
    notes: "Nghỉ học nhiều ảnh hưởng tới kết quả tiếp thu bài. Cần bồi dưỡng hè các môn Toán, Khoa học tự nhiên để thi lại.",
    verificationToken: "VERIFY-HS202605-CHUVANAN-6A5-2526",
    subjects: [
      { subjectId: "toan", subjectName: "Toán học", isEvaluatedByScore: true, mid1: 4.0, end1: 3.5, semester1: 3.7, mid2: 4.5, end2: 4.0, semester2: 4.2, yearAvg: 4.0 },
      { subjectId: "ly_dia", subjectName: "Lịch sử và Địa lí", isEvaluatedByScore: true, mid1: 5.0, end1: 4.5, semester1: 4.7, mid2: 5.5, end2: 5.0, semester2: 5.2, yearAvg: 5.0 },
      { subjectId: "khtn", subjectName: "Khoa học tự nhiên", isEvaluatedByScore: true, mid1: 3.5, end1: 4.0, semester1: 3.8, mid2: 4.0, end2: 4.0, semester2: 4.0, yearAvg: 3.9 },
      { subjectId: "tin", subjectName: "Tin học", isEvaluatedByScore: true, mid1: 5.0, end1: 5.0, semester1: 5.0, mid2: 5.0, end2: 5.0, semester2: 5.0, yearAvg: 5.0 },
      { subjectId: "van", subjectName: "Ngữ văn", isEvaluatedByScore: true, mid1: 5.0, end1: 5.0, semester1: 5.0, mid2: 5.5, end2: 5.0, semester2: 5.2, yearAvg: 5.1 },
      { subjectId: "anh", subjectName: "Ngoại ngữ", isEvaluatedByScore: true, mid1: 4.5, end1: 5.0, semester1: 4.8, mid2: 5.0, end2: 4.5, semester2: 4.7, yearAvg: 4.7 },
      { subjectId: "gdcd", subjectName: "GDCD", isEvaluatedByScore: true, mid1: 6.0, end1: 6.0, semester1: 6.0, mid2: 6.0, end2: 5.5, semester2: 5.7, yearAvg: 5.8 },
      { subjectId: "cong_nghe", subjectName: "Công nghệ", isEvaluatedByScore: true, mid1: 5.0, end1: 5.0, semester1: 5.0, mid2: 5.0, end2: 5.0, semester2: 5.0, yearAvg: 5.0 },
      { subjectId: "the_duc", subjectName: "Giáo dục thể chất", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
      { subjectId: "nghe_thuat", subjectName: "Nghệ thuật", isEvaluatedByScore: false, semester1: "Chưa đạt", semester2: "Đạt", yearAvg: "Đạt" },
      { subjectId: "gd_dia_phuong", subjectName: "Nội dung giáo dục của địa phương", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
      { subjectId: "trai_nghiem", subjectName: "Hoạt động trải nghiệm, hướng nghiệp", isEvaluatedByScore: false, semester1: "Đạt", semester2: "Đạt", yearAvg: "Đạt" },
    ]
  }
];
